version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      pip-weekly:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "dependencies"
